#!/bin/bash

echo "🚀 YouTube Subscription Manager Setup"
echo "===================================="
echo ""
echo "This script will help you set up the Google Cloud Console configuration."
echo ""
echo "📋 Prerequisites:"
echo "1. Google Cloud Console account"
echo "2. A Google Cloud project"
echo ""
echo "🔧 Setup Steps:"
echo ""
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Create a new project or select existing one"
echo "3. Enable YouTube Data API v3:"
echo "   - APIs & Services > Library"
echo "   - Search for 'YouTube Data API v3'"
echo "   - Click 'Enable'"
echo ""
echo "4. Create OAuth 2.0 credentials:"
echo "   - APIs & Services > Credentials"
echo "   - Click 'Create Credentials' > 'OAuth client ID'"
echo "   - Application type: 'Web application'"
echo "   - Authorized JavaScript origins:"
echo "     * http://localhost:5173 (for development)"
echo "     * http://your-domain.com (for production)"
echo "   - Click 'Create'"
echo ""
echo "5. Get your credentials:"
echo "   - Copy the 'Client ID'"
echo "   - Copy the 'API key' (if available)"
echo ""
echo "6. Update the .env file:"
echo "   - Open .env file in this directory"
echo "   - Replace 'your_google_client_id_here' with your actual Client ID"
echo "   - Replace 'your_google_api_key_here' with your actual API key"
echo ""
echo "7. Start the development server:"
echo "   npm run dev"
echo ""
echo "8. Open your browser to: http://localhost:5173"
echo ""
echo "📖 For more details, see the README.md file"
echo ""
echo "Press Enter to continue..."
read -p ""

echo "✅ Setup instructions displayed!"
echo ""
echo "Next steps:"
echo "1. Configure your Google Cloud Console"
echo "2. Update the .env file with your credentials"
echo "3. Run 'npm run dev' to start the application"
echo ""
echo "Happy coding! 🎉"